services:
  - type: web
    name: choretracker
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate"
    startCommand: "gunicorn choretracker.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: choretracker-db
          property: connectionString
      - key: PYTHON_VERSION
        value: "3.11.0"

databases:
  - name: choretracker-db
    databaseName: choretracker
    user: choretracker
