# Generated by Django 4.2.14 on 2026-04-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_tasks', '0002_bad_deeds'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='calendartask',
            new_name='calendar_ta_family__adf90a_idx',
            old_name='calendar_ta_family_idx',
        ),
        migrations.RenameIndex(
            model_name='calendartask',
            new_name='calendar_ta_assigne_6d4356_idx',
            old_name='calendar_ta_assigne_idx',
        ),
        migrations.AlterField(
            model_name='baddeed',
            name='negative_points',
            field=models.IntegerField(help_text='Points to deduct (enter positive number, will be negated)'),
        ),
    ]
