# Generated by Django 4.2.14 on 2026-04-20 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calendar_tasks', '0003_rename_calendar_ta_family_idx_calendar_ta_family__adf90a_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarTaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed - Awaiting Approval'), ('approved', 'Approved ✅'), ('rejected', 'Rejected ❌')], default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=200)),
                ('note', models.TextField(blank=True, help_text='Note from kid when marking as done')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_child_tasks', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(limit_choices_to={'role': 'child'}, on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_assignments', to='calendar_tasks.calendartask')),
            ],
            options={
                'indexes': [models.Index(fields=['assigned_to', 'status'], name='calendar_ta_assigne_8c0c3b_idx')],
                'unique_together': {('task', 'assigned_to')},
            },
        ),
    ]
