# Generated by Django 4.2.14 on 2026-04-20 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0001_initial'),
        ('calendar_tasks', '0004_calendartaskassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendartaskassignment',
            name='chore_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_assignments', to='chores.choreassignment'),
        ),
    ]
