# Generated by Django 4.2.14 on 2026-04-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_password_reset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(choices=[('🦁', 'Lion'), ('🐯', 'Tiger'), ('🦊', 'Fox'), ('🐻', 'Bear'), ('🐼', 'Panda'), ('🐨', 'Koala'), ('🦄', 'Unicorn'), ('🐸', 'Frog'), ('🐙', 'Octopus'), ('🦋', 'Butterfly'), ('🐬', 'Dolphin'), ('🦅', 'Eagle')], default='🦁', max_length=10),
        ),
    ]
